import { AccountInfo } from '../../models';
import { FormState } from '../../types';

export const accountSettingsFormConfig: FormState<AccountInfo> = {
    logo: {
        error: '',
        value: '',
        label: 'Logo',
        type: 'text',
    },
    registeredName: {
        error: '',
        value: '',
        label: 'Registered Name',
        type: 'text',
        placeholder: 'Truss Manufacturer (PTY) Ltd.',
        required: false,
    },
    tradingName: {
        error: '',
        value: '',
        label: 'Trading Name',
        type: 'text',
        placeholder: 'Truss Manufacturer',
        required: false,
    },
    registrationNo: {
        error: '',
        value: '',
        label: 'Registration No.',
        type: 'text',
        placeholder: '2000/000000/23',
        required: false,
    },
    vatNo: {
        error: '',
        value: '',
        label: 'VAT No.',
        type: 'text',
        placeholder: '4000010006',
        required: false,
    },
    tel: {
        error: '',
        value: '',
        label: 'Tel',
        type: 'text',
        placeholder: '0126784123',
        required: true,
    },
    altTel: {
        error: '',
        value: '',
        label: 'Alt. Tel',
        type: 'text',
        placeholder: '0829874321',
        required: false,
    },
    email: {
        error: '',
        value: '',
        label: 'Email',
        type: 'email',
        placeholder: 'you@somewhere.co.za',
        required: true,
    },
    web: {
        error: '',
        value: '',
        label: 'Website',
        type: 'text',
        placeholder: 'www.somewhere.co.za',
        required: false,
    },
    address: {
        error: '',
        value: '',
        label: 'Address',
        type: 'textarea',
        placeholder: '123 Main Street, City, Country',
        required: true,
        style: { minHeight: 50 },
    },
};
